package GUI;

import civitas.TituloPropiedad;

/**
 * @author Jesús Navarro Merino
 * @author José Alberto Gómez García
 */

public class PropiedadPanel extends javax.swing.JPanel {
    private TituloPropiedad tituloPropiedad;
    
    /**
     * Creates new form PropiedadPanel
     */
    public PropiedadPanel() {
        initComponents();
    }
    
    void setPropiedad(TituloPropiedad tit) {
        tituloPropiedad = tit;
        
        mostrar_nombre_titulo.setText(tituloPropiedad.getNombre());
        
        String casas = Double.toString(tituloPropiedad.getNumCasas());
        mostrar_numero_casas.setText(casas);
        
        String hoteles=Double.toString(tituloPropiedad.getNumHoteles());
        mostrar_numero_hoteles.setText(hoteles);
        
        String hipotecado;
        if(tituloPropiedad.getHipotecado())
            hipotecado="Si";
        else
            hipotecado="No";
        
        mostrar_hipotecado.setText(hipotecado);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mostrar_nombre_titulo = new javax.swing.JTextField();
        mostrar_numero_casas = new javax.swing.JTextField();
        mostrar_numero_hoteles = new javax.swing.JTextField();
        mostrar_hipotecado = new javax.swing.JTextField();

        jLabel1.setText("Titulo:");

        jLabel2.setText("Numero Casas:");

        jLabel3.setText("Numero Hoteles:");

        jLabel4.setText("Hipotecado:");

        mostrar_nombre_titulo.setEditable(false);
        mostrar_nombre_titulo.setText("jTextField1");

        mostrar_numero_casas.setEditable(false);
        mostrar_numero_casas.setText("jTextField1");
        mostrar_numero_casas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrar_numero_casasActionPerformed(evt);
            }
        });

        mostrar_numero_hoteles.setEditable(false);
        mostrar_numero_hoteles.setText("jTextField1");

        mostrar_hipotecado.setEditable(false);
        mostrar_hipotecado.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mostrar_hipotecado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mostrar_numero_hoteles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mostrar_numero_casas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mostrar_nombre_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(mostrar_nombre_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(mostrar_numero_casas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(mostrar_numero_hoteles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(mostrar_hipotecado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mostrar_numero_casasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrar_numero_casasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mostrar_numero_casasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField mostrar_hipotecado;
    private javax.swing.JTextField mostrar_nombre_titulo;
    private javax.swing.JTextField mostrar_numero_casas;
    private javax.swing.JTextField mostrar_numero_hoteles;
    // End of variables declaration//GEN-END:variables
}
